# Generated by Django 3.2 on 2021-04-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ali', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='news',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews_ali.news', verbose_name='Новости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='url',
            field=models.SlugField(default=1, max_length=130, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='video',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reviews_ali.reviews', verbose_name='Видео'),
        ),
    ]
