# Generated by Django 3.2 on 2021-04-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ali', '0004_auto_20210411_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='news',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews_ali.reviews', verbose_name='Видео'),
        ),
    ]
