# Generated by Django 3.2 on 2021-04-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ali', '0006_news_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв для видео', 'verbose_name_plural': 'Отзывы для видео'},
        ),
        migrations.CreateModel(
            name='FeedbackNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('text', models.TextField(max_length=1000)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews_ali.news', verbose_name='Видео')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews_ali.feedbacknews', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв для новости',
                'verbose_name_plural': 'Отзывы для новостей',
            },
        ),
    ]
