# Generated by Django 3.2 on 2021-04-12 14:15

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ali', '0007_auto_20210411_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=1, verbose_name='Видео'),
            preserve_default=False,
        ),
    ]
