# Generated by Django 3.2 on 2021-04-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ali', '0009_alter_reviews_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews_ali.reviews', verbose_name='Видео'),
        ),
    ]
