# Generated by Django 3.2 on 2021-04-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ali', '0010_alter_feedback_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliexpress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('less_description', models.TextField(max_length=1000)),
                ('price', models.FloatField(default=0)),
                ('video', models.CharField(blank=True, max_length=500)),
                ('poster', models.ImageField(upload_to='ali_posters/')),
                ('photo', models.ImageField(upload_to='ali_photos/')),
                ('aliurl', models.URLField()),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Али-товар',
                'verbose_name_plural': 'Али-товары',
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='feedbacknews',
            name='text',
            field=models.TextField(max_length=3000),
        ),
    ]
