# Generated by Django 3.2 on 2021-04-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ali', '0011_auto_20210413_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliexpress',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews_ali.category', verbose_name='Категории'),
            preserve_default=False,
        ),
    ]
