# Generated by Django 3.2 on 2021-04-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ali', '0012_aliexpress_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacknews',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews_ali.news', verbose_name='Видео'),
        ),
    ]
