# Generated by Django 3.2 on 2021-04-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ali', '0013_alter_feedbacknews_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackNews',
        ),
    ]
